import {
  Code2,
  Server,
  Database,
  Palette,
  Globe,
  Cpu,
  Brain,
  Wrench,
  Layers,
  Terminal,
  Smartphone,
  Cloud,
  Shield,
  GitBranch,
  Boxes,
  LineChart,
  PenTool,
  Camera,
  Music,
  Languages,
  BookOpen,
  FlaskConical,
  Atom,
  Rocket,
  Gamepad2,
  Video,
  Mic,
  Users,
  Briefcase,
  Settings,
  Network,
  Bot,
  Sparkles,
  Zap,
  Puzzle,
  Wifi,
  Lock,
  BarChart3,
  Layout,
  Tag,
  type LucideIcon,
} from "lucide-react";

/** Curated icon set skill categories can pick from — kept small and legible instead of exposing all of lucide. */
export const SKILL_ICON_REGISTRY: Record<string, LucideIcon> = {
  Code2,
  Server,
  Database,
  Palette,
  Globe,
  Cpu,
  Brain,
  Wrench,
  Layers,
  Terminal,
  Smartphone,
  Cloud,
  Shield,
  GitBranch,
  Boxes,
  LineChart,
  PenTool,
  Camera,
  Music,
  Languages,
  BookOpen,
  FlaskConical,
  Atom,
  Rocket,
  Gamepad2,
  Video,
  Mic,
  Users,
  Briefcase,
  Settings,
  Network,
  Bot,
  Sparkles,
  Zap,
  Puzzle,
  Wifi,
  Lock,
  BarChart3,
  Layout,
};

export const SKILL_ICON_KEYS = Object.keys(SKILL_ICON_REGISTRY);

/** Fallback used when a category has no icon set yet, or references an unknown key. */
export const DEFAULT_SKILL_ICON: LucideIcon = Tag;

export function getSkillIcon(key?: string): LucideIcon {
  if (!key) return DEFAULT_SKILL_ICON;
  return SKILL_ICON_REGISTRY[key] || DEFAULT_SKILL_ICON;
}
